################################################################################
# Makefile for pokgame utilities ###############################################
################################################################################

all: tilemaker

tilemaker: tilemaker.c
	$(CC) -Werror -otilemaker tilemaker.c -ldstructs
